apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: custom-helm-app
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-12-17T10:11:09Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: vpromq01
  namespace: default
  resourceVersion: "8759"
  uid: e9c66039-1d4f-48fa-988d-ebf77da482fc
spec:
  clusterIP: 10.100.42.253
  clusterIPs:
  - 10.100.42.253
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: vpromq01
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
