apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vpromc.serviceName }}
spec:
  ports:
  - port: {{ .Values.vpromc.port }}
    targetPort: {{ .Values.vpromc.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.vpromc.name }}
  type: ClusterIP
