apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vprormq.serviceName }}
spec:
  ports:
  - port: {{ .Values.vprormq.port }}
    targetPort: {{ .Values.vprormq.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.vprormq.name }}
  type: ClusterIP
