apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vprormq.name }}  # Updated from rmqdep to vprormq
  labels:
    app: {{ .Values.vprormq.name }}  # Updated from rmqdep to vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.vprormq.name }}  # Updated from rmqdep to vprormq
  template:
    metadata:
      labels:
        app: {{ .Values.vprormq.name }}  # Updated from rmqdep to vprormq
    spec:
      containers:
      - name: {{ .Values.vprormq.name }}  # Updated from rmqdep to vprormq
        image: {{ .Values.vprormq.image }}  # Updated from rmqdep to vprormq
        ports:
        - name: rabbitmq-port
          containerPort: {{ .Values.vprormq.port }}  # Updated from rmqdep to vprormq
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vprormq.secretKeyRef.name }}  # Updated from rmqdep to vprormq
              key: {{ .Values.vprormq.secretKeyRef.key }}  # Updated from rmqdep to vprormq
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.vprormq.username }}  # Updated from rmqdep to vprormq
