apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-helm-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default  # Deploy to the 'default' namespace
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Ashsatsan/gitops-argocd.git  # Your GitHub repository
    targetRevision: HEAD  # Track the latest revision (or specify a branch)
    path: helm/projcharts  # Path to the Helm chart directory
    helm:
      releaseName: custom-helm-app
      parameters:
        - name: appimage
          value: "{{ .Values.appimage }}"  # Placeholder for image
        - name: apptag
          value: "{{ .Values.apptag }}"  # Placeholder for tag
  project: default  # Reference the ArgoCD project (default or custom)
