apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-helm-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Ashsatsan/gitops-argocd.git
    targetRevision: HEAD
    path: helm/projcharts
    helm:
      releaseName: custom-helm-app
      parameters:  # Use Helm parameters instead of values file
        - name: appimage
          value: ""  # You can leave this empty or remove it if not needed
        - name: apptag
          value: ""
  project: default
