apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-helm-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Ashsatsan/gitops-argocd.git  # Your Git repository
    targetRevision: HEAD
    path: helm/projcharts  # Path to your Helm chart
    helm:
      releaseName: custom-helm-app
      parameters:
        - name: appimage
          value: '202533515324.dkr.ecr.us-east-2.amazonaws.com/projstack'  # Use Helm values
        - name: apptag
          value: 'latest'  # Use Helm values
  project: default
