apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Ashsatsan/gitops-argocd.git
    targetRevision: main
    path: helm/projcharts
    helm:
      releaseName: custom-helm-app
      valueFiles:
        - values.yaml      
      parameters:
        - name: appimage
          value: "{{ secrets.REGISTRY }}/{{ secrets.ECR_REPO_NAME }}"  # Dynamic image repo
        - name: apptag
          value: "{{ env.IMAGE_TAG }}"  # Dynamic image tag
  project: default

  syncPolicy:
    automated:
      prune: true  # Automatically delete resources no longer tracked
      selfHeal: true 
