apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project1-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ashsatsan/gitops-argocd.git'
    targetRevision: main
    path: helm/projcharts
    helm:
      valueFiles:
        - values.yaml                # Default configurations          
  destination:
    server: https://kubernetes.default.svc
    namespace: default          # Target namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
