apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project1-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL:   # Replace with your GitHub repository URL
    targetRevision: main  # Change to the desired branch or commit SHA
    path: ./helm/projcharts  # Path to your Helm charts in the Git repository
  syncPolicy:
    automated:
      prune: true  # Automatically delete resources not in the source
      selfHeal: true  