apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-helm-app
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Ashsatsan/gitops-argocd.git
    targetRevision: HEAD
    path: helm/projcharts
    helm:
      releaseName: custom-helm-app
      values: ./helm/projcharts/values-override.yaml  # Reference to dynamically generated file
  project: default
