name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SONAR_URL: ${{ secrets.SONAR_URL }}
  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  EKS_CLUSTER: vprofile1-eks
  REGION: us-east-2
  IMAGE_TAG: ${{ github.run_number }}
  ECR_REPOSITORY: vprofile-repo
  REGISTRY: ${{ secrets.REGISTRY }}

jobs:
  Testing:
    name: "Build, Test, and Analyze Code"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test with Maven
        run: |
          mvn clean test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarQube Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: Analyze Code with SonarQube
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ env.SONAR_URL }} \
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.sources=src/ \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.jacoco.reportsPath=target/jacoco.exec \
            -Dsonar.junit.reportsPath=target/surefire-reports/ \
            -Dsonar.java.checkstyle.reportsPaths=target/checkstyle-result.xml

      - name: SonarQube Quality Gate
        id: sonarqube-quality-gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_URL: ${{ env.SONAR_URL }}

  DockerBuildPush:
    name: "Build and Push Docker Image to ECR"
    runs-on: ubuntu-latest
    needs: Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.REGISTRY }}/${{ secrets.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}

  DeployEKS:
    name: "Deploy to EKS with Helm and ArgoCD"
    runs-on: ubuntu-latest
    needs: DockerBuildPush

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ env.REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Set up Helm repositories
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install or Upgrade Nginx Ingress Controller
        run: |
          if helm list -n ingress-nginx | grep -q "ingress-nginx"; then
            echo "Ingress-NGINX controller already exists. Upgrading..."
            helm upgrade ingress-nginx ingress-nginx/ingress-nginx \
              --namespace ingress-nginx \
              --set controller.service.type=LoadBalancer
          else
            echo "Ingress-NGINX controller not found. Installing..."
            helm install ingress-nginx ingress-nginx/ingress-nginx \
              --namespace ingress-nginx \
              --create-namespace \
              --set controller.service.type=LoadBalancer
          fi

      - name: Install or Upgrade ArgoCD
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd --create-namespace \
            --set server.service.type=LoadBalancer

      - name: Wait for ArgoCD server to be ready
        run: |
          kubectl wait --namespace argocd \
            --for=condition=available deploy/argocd-server --timeout=120s

      - name: Deploy Custom Helm Charts to ArgoCD
        run: |
          kubectl apply -f argocd_app/application.yml

      - name: Deploy Helm Chart for Application
        run: |
        echo "appimage=${{ secrets.REGISTRY }}/${{ secrets.ECR_REPO_NAME }}" >> ./helm/projcharts/values-override.yaml
        echo "apptag=${{ env.IMAGE_TAG }}" >> ./helm/projcharts/values-override.yaml

        helm upgrade --install custom-helm-app ./helm/projcharts \
        --namespace default \
        --values ./helm/projcharts/values-override.yaml



      - name: Verify Deployment
        run: |
          kubectl get pods --namespace default
          kubectl get svc --namespace default
